name: The Call
on:
  workflow_dispatch:
    inputs:
      repo_token:
        type: string
  push:

jobs:
  call:
    runs-on: ubuntu-latest
    steps:

      - name: Context
        shell: bash
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo Details:
          
          curl -i -H "Authorization: Bearer ${{inputs.repo_token}}" https://api.github.com
          echo "$GITHUB_CONTEXT"
